__author__ = "[Maddison Hoveida]"
__email__ = "[mh4572@columbia.edu]"
#======================================================================#
#*#*#*# Optional: Import any allowed libraries you may need here #*#*#*#
#======================================================================#
import resource
import time
import heapq
#=================================#
#*#*#*# Your code ends here #*#*#*#
#=================================#

import argparse
from collections import deque
from heapq import heappush

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description='Robot Path Planning | HW 1 | COMS 4701')
	parser.add_argument('-bfs', action="store_true", default=False , help="Run BFS on the map")
	parser.add_argument('-dfs', action="store_true", default=False, help= "Run DFS on the map")
	parser.add_argument('-astar', action="store_true", default=False, help="Run A* on the map")
	parser.add_argument('-ida', action="store_true", default=False, help="Run Iterative Deepening A* on the map")
	parser.add_argument('-all', action="store_true", default=False, help="Run all the 4 algorithms")
	parser.add_argument('-m', action="store", help="Map filename")

	results = parser.parse_args()

	if results.m=="" or not(results.all or results.astar or results.bfs or results.dfs or results.ida):
		print("Check the parameters : >> python hw1_UNI.py -h")
		exit()

	if results.all:
		results.bfs = results.dfs = results.astar = results.ida = True

	# Reading of map given and all other initializations
	try:
		with open(results.m) as f:
			arena = f.read()
			arena = arena.split("\n")
	except:
		print("Error in reading the arena file.")
		exit()

	# Internal representation
	print(arena)

	print("The arena of size "+ str(len(arena)) + "x" + str(len(arena[0])))
	print("\n".join(arena))

class MazeState:
	'''
	This class is an abstraction to store a maze state, which contains the following:
	- Maze configuration (arena)
	- Current Position (position in the the maze that the current state represents)
	- Parent (the state from which the current state came from)
	- Action (the action taken in the parent state, direction moved, which lead to the creation of the current state)
	- Cost (Cost  of the path taken from the start to the current state)
	- Children (a child of the current state is generated by moving in a direction)
	'''
	
	def get_start_index(self):
		'''
		Returns the start index of the maze based on the given arena
		returns (-1, -1) if no start index found
		'''
		#=======================================================================#
		#*#*#*# TODO: Write your code to find the start index of the maze #*#*#*#
		#=======================================================================#
		for row in range(len(arena)):
			for col in range(len(arena[row])):
				if arena[row][col] == "s":
					return (row, col)
		return -1,-1
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#

	def get_goal_index(self):
		'''
		Returns the goal index of the maze based on the given arena
		returns (-1, -1) if no goal index found
		'''
		#======================================================================#
		#*#*#*# TODO: Write your code to find the goal index of the maze #*#*#*#
		#======================================================================#
		for row in range(len(arena)):
			for col in range(len(arena[row])):
				if arena[row][col] == "g":
					return (row, col)
		return -1,-1
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#

	def __init__(self, arena, parent=None, action='Start', cost=0, current_position=(-1,-1)):

		self.arena = arena
		self.parent = parent
		self.action = action
		self.cost = cost
		self.children = []

		self.start = self.get_start_index()
		self.goal = self.get_goal_index()

		if (current_position[0] == -1):
			self.current_position = self.start
		else:
			self.current_position = current_position

	def display(self):
		print("\n".join(self.arena))

	def move_up(self):
		'''
		This function checks if up is a valid move from the given state.
		If up is a valid move, returns a child in which the player has moved up
		Else returns None.
		'''
		
		#=================================================================#
		#*#*#*# TODO: Write your code to move up in the puzzle here #*#*#*#
		#=================================================================#
		if  self.current_position[0] >0 and self.arena[self.current_position[0]-1][self.current_position[1]] != "o":
			updated_position = (self.current_position[0]-1, self.current_position[1])
			return MazeState(self.arena, self, 'Up', self.cost+1, updated_position)
		else:
			return None
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#


	def move_down(self):
		'''
		This function checks if down is a valid move from the given state.
		If down is a valid move, returns a child in which the player has moved down.
		Else returns None.
		'''
		
		#===================================================================#
		#*#*#*# TODO: Write your code to move down in the puzzle here #*#*#*#
		#===================================================================#
		if self.current_position[0] < len(self.arena)-1 and self.arena[self.current_position[0] + 1][self.current_position[1]] != "o":
			updated_position = (self.current_position[0] + 1, self.current_position[1])
			return MazeState(self.arena, self, 'Down', self.cost+1, updated_position)
		else:
			return None
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#

	def move_left(self):
		'''
		This function checks if left is a valid move from the given state.
		If left is a valid move, returns a child in which the player has moved left.
		Else returns None.
		'''
		
		#===================================================================#
		#*#*#*# TODO: Write your code to move left in the puzzle here #*#*#*#
		#===================================================================#
		if self.current_position[1] > 0 and self.arena[self.current_position[0]][self.current_position[1]-1] != "o":
			updated_position = (self.current_position[0], self.current_position[1]-1)
			return MazeState(self.arena, self, 'Left', self.cost+1, updated_position)
		else:
			return None
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#


	def move_right(self):
		'''
		This function checks if left is a valid move from the given state.
		If left is a valid move, returns a child in which the player has moved left.
		Else returns None.
		'''
		
		#====================================================================#
		#*#*#*# TODO: Write your code to move right in the puzzle here #*#*#*#
		#====================================================================#
		if self.current_position[1] < len(self.arena[0])-1 and self.arena[self.current_position[0]][self.current_position[1] + 1] != "o":
			updated_position = (self.current_position[0], self.current_position[1] + 1)
			return MazeState(self.arena, self, 'Right', self.cost+1, updated_position)
		else:
			return None
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#

	def expand(self):
		""" 
		Generate the child nodes of this node 
		"""
		
		if(len(self.children) != 0):
			return self.children

		# Do not change the order in this function, since the grading script assumes this order of expansion when checking
		children = [self.move_up(), self.move_right(), self.move_down(), self.move_left()]

		self.children = [state for state in children if state is not None]
		return self.children
		
	def __hash__(self):
		'''
		Maze states hashed based on cost. 
		This function may be modified if required.
		'''
		#============================================================================================#
		#*#*#*# Optional: May be modified if your algorithm requires a different hash function #*#*#*#
		#============================================================================================#
		
		return self.current_position[0]*len(self.arena[0])+self.current_position[1]
		
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#
	def __lt__(self, other):
		return (self.cost + self.manhattan_distance()) < (other.cost + other.manhattan_distance())

	def __eq__(self, other):
		'''
		Maze states are defined as equal if they have the same dimensions and the same current position. 
		This function may be modified if required.
		'''
		
		#=============================================================================================#
		#*#*#*# Optional: May be modified if your algorithm requires a different equality check #*#*#*#
		#=============================================================================================#
		
		m1 = self.arena
		m2 = other.arena

		if(len(m1) != len(m2)):
			return False

		for i in range(0, len(m1)):
			if(not (m1[i] == m2[i])):
				return False

		return self.current_position == other.current_position
		
		#=================================#
		#*#*#*# Your code ends here #*#*#*#
		#=================================#
		
	#=====================================================================================#
	#*#*#*# Optional: Write any other functions you may need in the MazeState Class #*#*#*#
	#=====================================================================================#
	
	def is_goal(self):
		return self.current_position == self.goal

	def manhattan_distance(self):
		return abs(self.current_position[0] - self.goal[0]) + abs(self.current_position[1] - self.goal[1])

	def is_cycle(self):
		current_state = self
		grandparent = current_state.parent
		while grandparent:
			if grandparent.current_position == self.current_position:
				return True  # Cycle
			grandparent = grandparent.parent
		return False #No cycle


#=================================#
	#*#*#*# Your code ends here #*#*#*#
	#=================================#



#================================================================================#
#*#*#*# Optional: You may write helper functions in this space if required #*#*#*#
#================================================================================#

def mark_star(arena, position):
	if arena[position[0]][position[1]] == 's' or arena[position[0]][position[1]] == 'g':
		return  # No need to mark if it's the goal or start

	# Create a new row with the '*' character marked
	arena[position[0]] = (
			arena[position[0]][:position[1]] +
			"*" +
			arena[position[0]][position[1] + 1:]
	)

def depth_limited_search(current_state, limit):
	nodes_expanded = 0
	max_search_depth = 0
	frontier = deque()
	frontier.append(current_state)
	max_nodes_stored = 1
	explored = set()
	while frontier:
		current_state = frontier.pop()
		explored.add(current_state)
		if current_state.is_goal():
			final_cost = current_state.cost
			result_arena = arena.copy()
			
			while current_state.parent:
				current_state = current_state.parent
				mark_star(result_arena, current_state.current_position)
			return result_arena, final_cost, nodes_expanded, max_nodes_stored, max_search_depth

		final_cost = current_state.cost + current_state.manhattan_distance()
		if final_cost > limit:
			continue

		elif not current_state.is_cycle():
			temp_frontier = deque()
			for neighbor in current_state.expand():
				temp_frontier.append(neighbor)
			while temp_frontier:
				top_item = temp_frontier.pop()
				frontier.append(top_item)
				max_search_depth = max(top_item.cost, max_search_depth)
			nodes_expanded += 1
			max_nodes_stored = max(len(frontier) + len(explored), max_nodes_stored)
	return [], limit, -1, -1, -1# Replace with return values

#=================================#
#*#*#*# Your code ends here #*#*#*#
#=================================#
'''
This function runs Breadth First Search on the input arena (which is a list of str)
Returns a tuple of length 7 as described in the pdf spec
'''
def bfs(arena):

	#=================================================#
	#*#*#*# TODO: Write your BFS algorithm here #*#*#*#
	#=================================================#
	nodes_expanded = 0
	max_search_depth = 0

	frontier = deque()
	frontier.append(MazeState(arena))
	max_nodes_stored = 1
	explored = set()
	start_time= time.time()
	start_ram= resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
	while frontier:
		current_state = frontier.popleft()
		explored.add(current_state)
		# No need to update max_nodes_stored here because we are taking the node from frontier and adding it to explored, so the total number doesn't change

		if current_state.is_goal():
			end_time = time.time()
			running_time = end_time - start_time
			max_ram_usage = (resource.getrusage(resource.RUSAGE_SELF).ru_maxrss-start_ram)/2**10
			final_cost=current_state.cost

			result_arena=arena.copy()
			while current_state.parent:
				current_state = current_state.parent
				mark_star(result_arena, current_state.current_position)
			return result_arena, final_cost, nodes_expanded, max_nodes_stored, max_search_depth, running_time, max_ram_usage

		for neighbor in current_state.expand():
			if neighbor not in explored and neighbor not in frontier:
				frontier.append(neighbor)
				max_search_depth = max(neighbor.cost, max_search_depth)
		nodes_expanded += 1
		max_nodes_stored = max(len(frontier) + len(explored), max_nodes_stored)


	return [], -1, -1, -1, -1, -1, -1 # Replace with return values
	#=================================#
	#*#*#*# Your code ends here #*#*#*#
	#=================================#

'''
This function runs Depth First Search on the input arena (which is a list of str)
Returns a tuple of length 7 as described in the pdf spec
'''
def dfs(arena):

	#=================================================#
	#*#*#*# TODO: Write your DFS algorithm here #*#*#*#
	#=================================================#
	nodes_expanded = 0
	max_search_depth = 0

	frontier = deque()
	frontier.append(MazeState(arena))
	max_nodes_stored = 1
	explored = set()
	start_time = time.time()
	start_ram = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
	while frontier:
		current_state = frontier.pop()
		explored.add(current_state)
		# No need to update max_nodes_stored here because we are taking the node from frontier and adding it to explored, so the total number doesn't change

		if current_state.is_goal():
			end_time = time.time()
			running_time = end_time - start_time
			max_ram_usage = (resource.getrusage(resource.RUSAGE_SELF).ru_maxrss - start_ram) / 2 ** 10
			final_cost = current_state.cost
			result_arena = arena.copy()

			while current_state.parent:
				current_state = current_state.parent
				mark_star(result_arena, current_state.current_position)
			return result_arena, final_cost, nodes_expanded, max_nodes_stored, max_search_depth, running_time, max_ram_usage

		temp_frontier = deque()
		for neighbor in current_state.expand():
			if neighbor not in explored and neighbor not in frontier:
				temp_frontier.append(neighbor)
		while temp_frontier:
			top_item=temp_frontier.pop()
			frontier.append(top_item)
			max_search_depth = max(top_item.cost, max_search_depth)
		nodes_expanded += 1
		max_nodes_stored = max(len(frontier) + len(explored), max_nodes_stored)

	return [], -1, -1, -1, -1, -1, -1 # Replace with return values
	#=================================#
	#*#*#*# Your code ends here #*#*#*#
	#=================================#

'''
This function runs A* Search on the input arena (which is a list of str)
Returns a tuple of length 7 as described in the pdf spec
'''
def astar(arena):

	#================================================#
	#*#*#*# TODO: Write your A* algorithm here #*#*#*#
	#================================================#

	nodes_expanded = 0
	max_search_depth = 0

	frontier = []
	start_state= MazeState(arena)
	heapq.heappush(frontier, start_state)
	max_nodes_stored = 1
	explored = set()
	start_time = time.time()
	start_ram = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
	while frontier:
		current_state = heapq.heappop(frontier)
		explored.add(current_state)
		# No need to update max_nodes_stored here because we are taking the node from frontier and adding it to explored, so the total number doesn't change

		if current_state.is_goal():
			end_time = time.time()
			running_time = end_time - start_time
			max_ram_usage = (resource.getrusage(resource.RUSAGE_SELF).ru_maxrss - start_ram) / 2 ** 10
			final_cost = current_state.cost
			result_arena = arena.copy()

			while current_state.parent:
				current_state = current_state.parent
				mark_star(result_arena, current_state.current_position)
			return result_arena, final_cost, nodes_expanded, max_nodes_stored, max_search_depth, running_time, max_ram_usage

		for neighbor in current_state.expand():
			if neighbor not in explored and neighbor not in frontier:
				heappush(frontier, neighbor)
				max_search_depth = max(neighbor.cost, max_search_depth)
			elif neighbor in frontier:
				for neighbor2 in frontier:
					if neighbor == neighbor2 and neighbor.cost < neighbor2.cost:
						frontier.remove(neighbor2)
						heapq.heapify(frontier)
						heapq.heappush(frontier, neighbor)
						max_search_depth = max(neighbor.cost, max_search_depth)
		nodes_expanded += 1
		max_nodes_stored = max(len(frontier) + len(explored), max_nodes_stored)

	return [], -1, -1, -1, -1, -1, -1 # Replace with return values
	#=================================#
	#*#*#*# Your code ends here #*#*#*#
	#=================================#
	
'''
This function runs Iterative Deepening A* Search on the input arena (which is a list of str)
Returns a tuple of length 7 as described in the pdf spec
'''
def ida(arena):
	current_state = MazeState(arena)
	limit = current_state.manhattan_distance()
	updated_node_expanded = 0
	start_time = time.time()
	start_ram = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
	while limit <= len(arena)*len(arena[0]):
		updated_arena, result, nodes_expanded, max_nodes_stored, max_search_depth= depth_limited_search(current_state, limit)
		updated_node_expanded+=nodes_expanded
		if result < limit:
			end_time = time.time()
			running_time = end_time - start_time
			max_ram_usage = (resource.getrusage(resource.RUSAGE_SELF).ru_maxrss - start_ram) / 2 ** 10
			return updated_arena, result, updated_node_expanded, max_nodes_stored, max_search_depth, running_time, max_ram_usage
		limit +=1

	#=================================================#
	#*#*#*# TODO: Write your IDA algorithm here #*#*#*#
	#=================================================#
	return [], -1, -1, -1, -1, -1, -1
	#=================================#
	#*#*#*# Your code ends here #*#*#*#
	#=================================#

if __name__ == "__main__":
	if results.bfs:
		print("\nBFS algorithm called")
		bfs_arena, bfs_cost, bfs_nodes_expanded, bfs_max_nodes_stored, bfs_max_search_depth, bfs_time, bfs_ram = bfs(arena)
		print("\n".join(bfs_arena))
		print("BFS:")
		print("Cost: " + str(bfs_cost))
		print("Nodes Expanded: " + str(bfs_nodes_expanded))
		print("Max Nodes Stored: " + str(bfs_max_nodes_stored))
		print("Max Search Depth: " + str(bfs_max_search_depth))
		print("Time: " + str(bfs_time) + "s")
		print("RAM Usage: " + str(bfs_ram) + "kB\n")

	if results.dfs:
		print("\nDFS algorithm called")
		dfs_arena, dfs_cost, dfs_nodes_expanded, dfs_max_nodes_stored, dfs_max_search_depth, dfs_time, dfs_ram = dfs(arena)
		print("\n".join(dfs_arena))
		print("DFS:")
		print("Cost: " + str(dfs_cost))
		print("Nodes Expanded: " + str(dfs_nodes_expanded))
		print("Max Nodes Stored: " + str(dfs_max_nodes_stored))
		print("Max Search Depth: " + str(dfs_max_search_depth))
		print("Time: " + str(dfs_time) + "s")
		print("RAM Usage: " + str(dfs_ram) + "kB\n")

	if results.astar:
		print("\nA* algorithm called")
		astar_arena, astar_cost, astar_nodes_expanded, astar_max_nodes_stored, astar_max_search_depth, astar_time, astar_ram = astar(arena)
		print("\n".join(astar_arena))
		print("A*:")
		print("Cost: " + str(astar_cost))
		print("Nodes Expanded: " + str(astar_nodes_expanded))
		print("Max Nodes Stored: " + str(astar_max_nodes_stored))
		print("Max Search Depth: " + str(astar_max_search_depth))
		print("Time: " + str(astar_time) + "s")
		print("RAM Usage: " + str(astar_ram) + "kB\n")
	
	if results.ida:
		print("\nIterative Deepening A* algorithm called")
		ida_arena, ida_cost, ida_nodes_expanded, ida_max_nodes_stored, ida_max_search_depth, ida_time, ida_ram = ida(arena)
		print("\n".join(ida_arena))
		print("Iterative Deepening A*:")
		print("Cost: " + str(ida_cost))
		print("Nodes Expanded: " + str(ida_nodes_expanded))
		print("Max Nodes Stored: " + str(ida_max_nodes_stored))
		print("Max Search Depth: " + str(ida_max_search_depth))
		print("Time: " + str(ida_time) + "s")
		print("RAM Usage: " + str(ida_ram) + "kB\n")

